site_name: Live 
dev_addr: 127.0.0.1:9001
theme:
  name: material
  logo: images/abletonlive.svg
  favicon: images/abletonlive.svg
  palette:
    scheme: black-white
    primary: custom
    accent: custom
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrated
nav:
  - Home: index.md
  - Manual:
  - Overview: Manual/00_manual.md
  - Audio Effects: Manual/01_audio_effects.md
  - Release Notes:
  - Overview: Release_Note/00_release_notes.md
  - Live 12: Release_Note/01_Live_12.md

extra_css:
  - stylesheets/extra.css